name: Serverless Deploy

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      working-directory:
        required: false
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.target-env }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: ./.github/actions/yarn-install
        with:
          cache-prefix: ${{ runner.os }}-v1

      - name: Serverless Deploy
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "Deploying to ${{ inputs.target-env }}"
          echo "yarn run sls:deploy --stage ${{ inputs.target-env }}"
