name: Serverless Deploy

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      working-directory:
        required: false
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.target-env }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: ./.github/actions/yarn-install
        with:
          cache-prefix: ${{ runner.os }}-v1

      - name: Serverless Deploy
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "Deploying to ${{ inputs.target-env }}"
          echo "yarn run sls:deploy --stage ${{ inputs.target-env }}"
