name: Dependency Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@01bc87099ba56df1e897b6874784491ea6309bc4 # v3
        with:
          comment-summary-in-pr: on-failure
