name: Serverless Typescript

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/serverless-typescript.yml'
      - '.github/workflows/_serverless-deploy.yml'
      - '.github/actions/yarn-install/**'
      - 'serverless-typescript/**'
      - '.yarn/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/serverless-typescript.yml'
      - '.github/workflows/_serverless-deploy.yml'
      - '.github/actions/yarn-install/**'
      - 'serverless-typescript/**'
      - '.yarn/**'
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch:
    inputs:
      target-env:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        uses: ./.github/actions/yarn-install
        with:
          cache-prefix: ${{ runner.os }}-v1

      - name: Test
        working-directory: serverless-typescript
        run: yarn run sls:invoke

      - name: Package
        working-directory: serverless-typescript
        run: yarn run sls:package

  deploy-staging:
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target-env == 'staging')
    needs: test-and-package
    uses: ./.github/workflows/_serverless-deploy.yml
    with:
      working-directory: serverless-typescript
      target-env: staging
    secrets: inherit

  deploy-production:
    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target-env == 'production')
    needs: deploy-staging
    uses: ./.github/workflows/_serverless-deploy.yml
    with:
      working-directory: serverless-typescript
      target-env: production
    secrets: inherit
